export const articlesData = [
  {
    id: 1,
    title: "World Spine Day 2025: Recognising Common Spine Disorders You Shouldn't Ignore",
    description: "The spine is the central support structure of the body, responsible for posture, movement, and protecting the spin...",
    imageUrl: "https://placehold.co/600x400/0891b2/ffffff?text=SPINE+HEALTH",
    imageTheme: "bg-cyan-600",
    imageOverlayText: "WORLD SPINE DAY",
    author: "Dr. Jitesh Manghwani",
    specialty: "Spine Surgery",
    date: "Oct 16, 2025",
    readTime: "4 min read",
  },
  {
    id: 2,
    title: "What is Hypoxemia: Causes, Symptoms, Treatment and Prevention",
    description: "Oxygen is essential for life, powering every cell and ensuring organs function properly. A reduction in blood oxygen level...",
    imageUrl: "https://placehold.co/600x400/99f6e4/0f766e?text=OXYGEN+LEVELS",
    imageTheme: "bg-teal-400",
    imageOverlayText: "WHAT IS HYPOXEMIA",
    author: "Dr. Vivek Nangia",
    specialty: "Pulmonology",
    date: "Oct 16, 2025",
    readTime: "12 min read",
  },
  {
    id: 3,
    title: "Air Pollution and Your Throat: Understanding the Connection",
    description: "Air pollution is a pervasive concern in today's world, with detrimental effects on human health. While we often...",
    imageUrl: "https://placehold.co/600x400/475569/f8fafc?text=AIR+POLLUTION",
    imageTheme: "bg-slate-500",
    imageOverlayText: "AIR POLLUTION AND YOUR THROAT",
    author: "Dr. Ravinder Gera",
    specialty: "Ear Nose Throat",
    date: "Oct 16, 2025",
    readTime: "5 min read",
  },
  {
    id: 4,
    title: "Ideal Blood Pressure: What the Numbers Really Mean for Your Health",
    description: "Blood pressure is often called the silent indicator of health. It quietly reflects how well your heart and blood vessels are...",
    imageUrl: "https://placehold.co/600x400/4c0519/fecaca?text=BLOOD+PRESSURE",
    imageTheme: "bg-rose-900",
    imageOverlayText: "IDEAL BLOOD PRESSURE",
    author: "Dr. Rajiv Agarwal",
    specialty: "Cardiology",
    date: "Oct 16, 2025",
    readTime: "4 min read",
  },
];