import {
  Baby,
  Bone,
  Brain,
  Droplets,
  FlaskConical,
  FlaskRound,
  Heart,
  HeartPulse,
  Hospital,
  Microscope,
  Salad,
  Scan,
  ShieldAlert,
  Stethoscope,
  Sun,
  Syringe,
  TestTube,
  Thermometer,
  Users,
} from "lucide-react";

import { CarouselItem } from "@/components/ourSpecialist/specialist_carosole";

export const OUR_SPECIALITIES: CarouselItem[] = [
  { title: "Accident & Emergency", icon: <ShieldAlert /> },
  { title: "Anesthesia and Pain Medicine", icon: <Syringe /> },
  { title: "Cancer Care Centre", icon: <FlaskConical /> },
  { title: "Cardiology Care Centre", icon: <HeartPulse /> },
  { title: "Cardiothoracic & Vascular Surgery", icon: <Stethoscope /> },
  { title: "Cardiothoracic Anaesthesia", icon: <Brain /> },
  { title: "Child Development Centre", icon: <Baby /> },
  { title: "Counselling Centre", icon: <Users /> },
  { title: "Critical Care Units", icon: <Hospital /> },
  { title: "Dental & Maxillofacial Surgery", icon: <Bone /> },
  { title: "Dermatology & Venereology", icon: <Sun /> },
  { title: "Diabetology & Endocrinology", icon: <Thermometer /> },
  { title: "Diagnostic & Interventional Radiology", icon: <Scan /> },
  { title: "Dietetics & Nutrition", icon: <Salad /> },
  { title: "ENT & Head Neck Surgery", icon: <Stethoscope /> },
  { title: "Fertility Centre", icon: <Heart /> },
  { title: "Gastroenterology & Hepatology", icon: <FlaskRound /> },
  { title: "General & Laparoscopic Surgery", icon: <Microscope /> },
  { title: "Haematology & Stem Cell Transplant", icon: <TestTube /> },
  { title: "Hepatobiliary, Pancreatic and Liver Transplant", icon: <Droplets /> },
  { title: "Internal Medicine", icon: <Brain /> },
  { title: "Joint Care & Wellness Centre", icon: <Bone /> },
  { title: "Kidney Transplant Program", icon: <Droplets /> },
  { title: "Lab Medicine", icon: <FlaskConical /> },
];
